import { NextResponse } from 'next/server';

export async function GET(req: Request) {
  const payments = [
    {
      id: 'pay-2026-10-01',
      invoice_number: 'LCA-INV-2026-10-006',
      receipt_number: 'LCA-REC-2026-10-006',
      fee_period: 'October 2026',
      course_title: 'Bharathanatyam',
      batch_name: 'Batch A (Beginners)',
      amount_paid: 2000,
      gross_amount: 2000,
      discount_amount: 0,
      balance_due: 0,
      payment_date: '02 Oct 2026',
      payment_date_iso: '2026-10-02',
      payment_method: 'UPI',
      transaction_reference: 'UPI/627581920391/HDFC',
      status: 'Paid',
      receipt_issued_by: 'Sri Ramesh Rao (Director)',
      student_name: 'Aditi Sundaram',
      roll_number: 'LCA-6',
      parent_name: 'Sri Sundaram V.',
      remarks: 'Tuition fee for October 2026 received via UPI QR',
    },
    {
      id: 'pay-2026-09-01',
      invoice_number: 'LCA-INV-2026-09-006',
      receipt_number: 'LCA-REC-2026-09-006',
      fee_period: 'September 2026',
      course_title: 'Bharathanatyam',
      batch_name: 'Batch A (Beginners)',
      amount_paid: 2000,
      gross_amount: 2000,
      discount_amount: 0,
      balance_due: 0,
      payment_date: '04 Sep 2026',
      payment_date_iso: '2026-09-04',
      payment_method: 'UPI',
      transaction_reference: 'UPI/592837190281/ICICI',
      status: 'Paid',
      receipt_issued_by: 'Sri Ramesh Rao (Director)',
      student_name: 'Aditi Sundaram',
      roll_number: 'LCA-6',
      parent_name: 'Sri Sundaram V.',
      remarks: 'Tuition fee for September 2026 received via UPI',
    },
    {
      id: 'pay-2026-08-01',
      invoice_number: 'LCA-INV-2026-08-006',
      receipt_number: 'LCA-REC-2026-08-006',
      fee_period: 'August 2026',
      course_title: 'Bharathanatyam',
      batch_name: 'Batch A (Beginners)',
      amount_paid: 2000,
      gross_amount: 2000,
      discount_amount: 0,
      balance_due: 0,
      payment_date: '02 Aug 2026',
      payment_date_iso: '2026-08-02',
      payment_method: 'UPI',
      transaction_reference: 'UPI/549102847291/SBI',
      status: 'Paid',
      receipt_issued_by: 'Sri Ramesh Rao (Director)',
      student_name: 'Aditi Sundaram',
      roll_number: 'LCA-6',
      parent_name: 'Sri Sundaram V.',
      remarks: 'Tuition fee for August 2026 received via UPI',
    },
    {
      id: 'pay-2026-07-01',
      invoice_number: 'LCA-INV-2026-07-006',
      receipt_number: 'LCA-REC-2026-07-006',
      fee_period: 'July 2026',
      course_title: 'Bharathanatyam',
      batch_name: 'Batch A (Beginners)',
      amount_paid: 2000,
      gross_amount: 2000,
      discount_amount: 0,
      balance_due: 0,
      payment_date: '05 Jul 2026',
      payment_date_iso: '2026-07-05',
      payment_method: 'Bank Transfer',
      transaction_reference: 'NEFT/AXIS/291827401',
      status: 'Paid',
      receipt_issued_by: 'Sri Ramesh Rao (Director)',
      student_name: 'Aditi Sundaram',
      roll_number: 'LCA-6',
      parent_name: 'Sri Sundaram V.',
      remarks: 'Tuition fee for July 2026 received via NEFT',
    },
    {
      id: 'pay-2026-06-REG',
      invoice_number: 'LCA-INV-2026-06-REG',
      receipt_number: 'LCA-REC-2026-06-REG',
      fee_period: 'Academic Year 2026-27 Admission',
      course_title: 'Bharathanatyam',
      batch_name: 'Batch A (Beginners)',
      amount_paid: 1500,
      gross_amount: 1500,
      discount_amount: 0,
      balance_due: 0,
      payment_date: '15 Jun 2026',
      payment_date_iso: '2026-06-15',
      payment_method: 'UPI',
      transaction_reference: 'UPI/492817293810/HDFC',
      status: 'Paid',
      receipt_issued_by: 'Sri Ramesh Rao (Director)',
      student_name: 'Aditi Sundaram',
      roll_number: 'LCA-6',
      parent_name: 'Sri Sundaram V.',
      remarks: 'Annual Academy Enrollment, ID Card & Practice Ghungroo kit',
    },
  ];

  return NextResponse.json(
    { success: true, payments },
    {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      },
    }
  );
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
  });
}
